### PR TITLE
Allow body for GET and HEAD for consistency

### PR DESCRIPTION
**Pull request by jhaber**

### CODE REVIEW

**Comment by jhaber** [comment]
We either need to disallow body on GET/HEAD/DELETE or allow on all three

**Comment by roderyc** [comment]
Hi :).
I was just about to make a pull request for this. Certain Elasticsearch apis require a GET with a body. As far as I can see, HTTP 1.1 doesn't forbid this, so why do that here?

**Comment by jhaber** [comment]
The spec says the server should ignore the body, and in the ElasticSearch [case](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html) isn't POST supported as well? 
> Since not all clients support GET with body, POST is allowed as well.

Also, the current behavior is often helpful if you forget to set the method to `POST` or `PUT` when constructing the request, for example this code throws an error with a helpful message:
```java
    HttpRequest request = HttpRequest.newBuilder()
        .setUrl(url)
        .setBody(body)
        .build();
```

But if `GET` with a body was allowed, the request would be sent and you would have to try to figure out the problem based on the cryptic response you receive (or in many cases the request will even succeed, but obviously not do what you want).

My feeling is that Horizon is meant for certain use-cases and intentionally not designed to support hitting every possible site on the internet (it fully buffers requests and responses in memory, for example, which simplifies things in our target use-case but makes other use-cases impractical). This seems to me like a use-case we don't want to target (hitting bad APIs that ignore the HTTP spec, how far down this rabbit hole do you go?) but if there's no workaround for ElasticSearch or if you have any other thoughts I'd be interested to hear them

**Comment by roderyc** [comment]
I've been using the Percolator APIs, which don't mention allowing POSTs. It turns out that they do, so thank you for the workaround!

Now that I don't have any skin in the game I agree that it's useful for horizon to optimize for the "well behaved Rest API with reasonably sized responses" use case and I'd support continuing to do so (i.e. making some sort of noise when a GET is set up with a body) :P.

**Comment by jhaber** [comment]
Closing for now

**Pull request closed without merging**
