### PR TITLE
Add support for multipart bodies

### PR DESCRIPTION
**Pull request by szabowexler**
Per the description, adds the ability to create multipart http requests.

### CODE REVIEW

**Comment by stevegutz** [comment]
@jhaber @kmclarnon

**Comment by stevegutz** [comment]
LGTM, though I'm not sure about that dep

**Comment by szabowexler** [comment]
I've verified that this does in fact allow us to send multipart bodies in a dependent project

**Comment by szabowexler** [comment]
Given the dep this adds, I've actually just done this directly in the slack client for now to avoid complicating horizon.

**Pull request closed without merging**
